from flask import Flask, render_template, request, send_file
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from datetime import datetime, date, timedelta
import pandas as pd
import os
import re

app = Flask(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
OUTPUT_FOLDER = os.path.join(BASE_DIR, "outputs")

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


# ============================================================
# TEXT HELPERS
# ============================================================

def clean_text(value):
    if value is None:
        return ""

    text = str(value).strip()

    text = re.sub(r"\s+", " ", text)

    return text


def normalize(value):
    return clean_text(value).lower()


# ============================================================
# DATE PARSER
# ============================================================

def parse_date(value):

    if value is None:
        return None

    if isinstance(value, datetime):
        return value.date()

    if isinstance(value, date):
        return value

    if isinstance(value, pd.Timestamp):
        return value.date()

    text = clean_text(value)

    if not text:
        return None

    formats = [
        "%m/%d/%Y",
        "%m/%d/%y",
        "%m-%d-%Y",
        "%m-%d-%y",
        "%Y-%m-%d",
        "%d/%m/%Y",
        "%d-%m-%Y",
    ]

    for fmt in formats:

        try:
            return datetime.strptime(
                text,
                fmt
            ).date()

        except:
            pass

    try:

        parsed = pd.to_datetime(
            text,
            errors="coerce"
        )

        if not pd.isna(parsed):

            return parsed.date()

    except:
        pass

    return None


# ============================================================
# FIND MASTER FILE
# ============================================================

def find_master_file():

    files = []

    for filename in os.listdir(BASE_DIR):

        if not filename.lower().endswith(
            (".xlsx", ".xls")
        ):
            continue

        # Don't consider files generated by the tool
        if filename.startswith("ORB_OOO_Schedule"):
            continue

        if filename.startswith("~$"):
            continue

        files.append(
            os.path.join(
                BASE_DIR,
                filename
            )
        )

    # Look for a workbook containing
    # Employee Name + Employee Code
    for filepath in files:

        try:

            excel = pd.ExcelFile(filepath)

            for sheet in excel.sheet_names:

                df = pd.read_excel(
                    filepath,
                    sheet_name=sheet,
                    nrows=10
                )

                columns = [
                    normalize(c)
                    for c in df.columns
                ]

                has_name = any(
                    c in [
                        "employee name",
                        "employee",
                        "name"
                    ]
                    for c in columns
                )

                has_code = any(
                    c in [
                        "employee code",
                        "employee_code",
                        "emp code",
                        "emp_code",
                        "code"
                    ]
                    for c in columns
                )

                if has_name and has_code:

                    return filepath, sheet

        except Exception:
            continue

    return None, None


# ============================================================
# LOAD MASTER EMPLOYEES
# ============================================================

def load_master():

    master_file, master_sheet = find_master_file()

    if not master_file:

        raise Exception(
            "Employee master file not found. "
            "Keep the master Excel file in the same folder as app.py "
            "with Employee Name and Employee Code columns."
        )

    df = pd.read_excel(
        master_file,
        sheet_name=master_sheet
    )

    # Map columns
    name_col = None
    code_col = None

    for col in df.columns:

        normalized = normalize(col)

        if normalized in [
            "employee name",
            "employee",
            "name"
        ]:
            name_col = col

        if normalized in [
            "employee code",
            "employee_code",
            "emp code",
            "emp_code",
            "code"
        ]:
            code_col = col

    if name_col is None or code_col is None:

        raise Exception(
            "Master file must contain Employee Name "
            "and Employee Code."
        )

    employees = []

    for _, row in df.iterrows():

        name = clean_text(
            row[name_col]
        )

        code = clean_text(
            row[code_col]
        )

        if name and code:

            employees.append({
                "name": name,
                "code": code
            })

    if not employees:

        raise Exception(
            "No employees were found in the master file."
        )

    return employees


# ============================================================
# READ OOO FILE
# ============================================================

def read_ooo_file(filepath):

    excel = pd.ExcelFile(filepath)

    records = []

    for sheet in excel.sheet_names:

        df = pd.read_excel(
            filepath,
            sheet_name=sheet
        )

        if df.empty:
            continue

        # Normalize column lookup
        column_map = {}

        for col in df.columns:

            column_map[
                normalize(col)
            ] = col

        date_col = None
        status_col = None
        name_col = None

        # DATE
        for key in [
            "date",
            "ooo date",
            "out of office date"
        ]:

            if key in column_map:

                date_col = column_map[key]
                break

        # STATUS
        for key in [
            "status",
            "ooo status"
        ]:

            if key in column_map:

                status_col = column_map[key]
                break

        # EMPLOYEE
        for key in [
            "employee name",
            "employee",
            "name"
        ]:

            if key in column_map:

                name_col = column_map[key]
                break

        if not date_col or not status_col or not name_col:
            continue

        for _, row in df.iterrows():

            ooo_date = parse_date(
                row[date_col]
            )

            employee_name = clean_text(
                row[name_col]
            )

            status = normalize(
                row[status_col]
            )

            if not ooo_date:
                continue

            if not employee_name:
                continue

            # Accept multiple ways of writing OOO
            is_ooo = status in [
                "ooo",
                "out of office",
                "out-of-office",
                "out_of_office",
                "outoffice"
            ]

            if not is_ooo:
                continue

            records.append({
                "date": ooo_date,
                "employee": employee_name
            })

    if not records:

        raise Exception(
            "No valid Out of Office records were found."
        )

    return records


# ============================================================
# GET WEEK
# ============================================================

def get_week(records):

    dates = [
        record["date"]
        for record in records
    ]

    first_date = min(dates)

    monday = (
        first_date -
        timedelta(
            days=first_date.weekday()
        )
    )

    return [
        monday + timedelta(days=i)
        for i in range(5)
    ]


# ============================================================
# CREATE REPORT
# ============================================================

def create_report(ooo_records):

    # --------------------------------------------------------
    # MASTER
    # --------------------------------------------------------

    employees = load_master()

    # --------------------------------------------------------
    # WEEK
    # --------------------------------------------------------

    week = get_week(
        ooo_records
    )

    # --------------------------------------------------------
    # MASTER LOOKUP
    # --------------------------------------------------------

    master_lookup = {}

    for employee in employees:

        master_lookup[
            normalize(employee["name"])
        ] = employee["code"]

    # --------------------------------------------------------
    # OOO BY DATE
    # --------------------------------------------------------

    ooo_by_date = {}

    for record in ooo_records:

        record_date = record["date"]

        employee_name = normalize(
            record["employee"]
        )

        # Match input employee to master
        employee_code = master_lookup.get(
            employee_name
        )

        if not employee_code:

            # Try partial matching
            for master_name, code in master_lookup.items():

                if (
                    employee_name == master_name
                    or
                    employee_name in master_name
                    or
                    master_name in employee_name
                ):

                    employee_code = code
                    break

        if not employee_code:
            continue

        if record_date not in ooo_by_date:

            ooo_by_date[record_date] = []

        if employee_code not in ooo_by_date[record_date]:

            ooo_by_date[
                record_date
            ].append(
                employee_code
            )

    # --------------------------------------------------------
    # ALL EMPLOYEE CODES
    # --------------------------------------------------------

    all_codes = []

    for employee in employees:

        code = employee["code"]

        if code not in all_codes:

            all_codes.append(code)

    # --------------------------------------------------------
    # WORKBOOK
    # --------------------------------------------------------

    wb = Workbook()

    ws = wb.active

    ws.title = "ORB Schedule"

    # --------------------------------------------------------
    # COLORS
    # --------------------------------------------------------

    BLACK = "000000"
    WHITE = "FFFFFF"

    BLUE = "00AEEF"
    YELLOW = "FFC000"

    LIGHT_GREY = "E7E6E6"

    RED = "C00000"

    # --------------------------------------------------------
    # COLUMN WIDTH
    # --------------------------------------------------------

    ws.column_dimensions["A"].width = 25

    for column in range(2, 7):

        ws.column_dimensions[
            chr(64 + column)
        ].width = 18

    # --------------------------------------------------------
    # HEADER
    # --------------------------------------------------------

    day_names = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
    ]

    for index in range(5):

        col = index + 2

        header = ws.cell(
            row=1,
            column=col
        )

        header.value = day_names[index]

        header.fill = PatternFill(
            "solid",
            fgColor=BLACK
        )

        header.font = Font(
            name="Calibri",
            size=12,
            bold=True,
            color=WHITE
        )

        header.alignment = Alignment(
            horizontal="left",
            vertical="center"
        )

        header.border = Border(
            left=Side(style="thin"),
            right=Side(style="thin"),
            top=Side(style="thin"),
            bottom=Side(style="thin")
        )

    # --------------------------------------------------------
    # DATES
    # --------------------------------------------------------

    for index, current_date in enumerate(
        week
    ):

        col = index + 2

        cell = ws.cell(
            row=2,
            column=col
        )

        cell.value = current_date

        cell.number_format = "m/d"

        cell.fill = PatternFill(
            "solid",
            fgColor=BLACK
        )

        cell.font = Font(
            name="Calibri",
            size=12,
            bold=True,
            color=WHITE
        )

        cell.alignment = Alignment(
            horizontal="left",
            vertical="center"
        )

        cell.border = Border(
            left=Side(style="thin"),
            right=Side(style="thin"),
            top=Side(style="thin"),
            bottom=Side(style="thin")
        )

    # --------------------------------------------------------
    # LABELS
    # --------------------------------------------------------

    ws["A3"] = "Online"
    ws["A4"] = "Out of Office"

    ws["A3"].fill = PatternFill(
        "solid",
        fgColor=BLUE
    )

    ws["A4"].fill = PatternFill(
        "solid",
        fgColor=YELLOW
    )

    ws["A3"].font = Font(
        name="Calibri",
        size=12,
        bold=True,
        color=WHITE
    )

    ws["A4"].font = Font(
        name="Calibri",
        size=12,
        bold=True,
        color=RED
    )

    # --------------------------------------------------------
    # DAILY CALCULATION
    # --------------------------------------------------------

    for index, current_date in enumerate(
        week
    ):

        col = index + 2

        # OOO employees for the day
        ooo_codes = ooo_by_date.get(
            current_date,
            []
        )

        # CRITICAL:
        # Online = everyone - OOO
        online_codes = []

        for code in all_codes:

            if code not in ooo_codes:

                online_codes.append(code)

        # ----------------------------------------------------
        # ONLINE CELL
        # ----------------------------------------------------

        online_cell = ws.cell(
            row=3,
            column=col
        )

        online_cell.value = "/".join(
            online_codes
        )

        # ----------------------------------------------------
        # OOO CELL
        # ----------------------------------------------------

        ooo_cell = ws.cell(
            row=4,
            column=col
        )

        ooo_cell.value = "/".join(
            ooo_codes
        )

        # ----------------------------------------------------
        # FORMAT
        # ----------------------------------------------------

        for cell in [
            online_cell,
            ooo_cell
        ]:

            cell.fill = PatternFill(
                "solid",
                fgColor=LIGHT_GREY
            )

            cell.border = Border(
                left=Side(style="thin"),
                right=Side(style="thin"),
                top=Side(style="thin"),
                bottom=Side(style="thin")
            )

            cell.alignment = Alignment(
                horizontal="left",
                vertical="center",
                wrap_text=True
            )

            cell.font = Font(
                name="Calibri",
                size=11
            )

        if ooo_codes:

            ooo_cell.font = Font(
                name="Calibri",
                size=11,
                bold=True,
                color=RED
            )

    # --------------------------------------------------------
    # OPERATIONAL ROWS
    # --------------------------------------------------------

    ws["A5"] = "TG2/TG3 Agenda"
    ws["A6"] = "Rewards IT Queue"
    ws["A7"] = "Remediations"

    for row in range(5, 8):

        ws.cell(
            row=row,
            column=1
        ).font = Font(
            name="Calibri",
            size=12
        )

    # --------------------------------------------------------
    # ROW HEIGHT
    # --------------------------------------------------------

    ws.row_dimensions[1].height = 25
    ws.row_dimensions[2].height = 25
    ws.row_dimensions[3].height = 35
    ws.row_dimensions[4].height = 35

    # --------------------------------------------------------
    # OUTPUT FILE
    # --------------------------------------------------------

    filename = (
        "ORB_OOO_Schedule_"
        + week[0].strftime("%Y%m%d")
        + "_"
        + week[-1].strftime("%Y%m%d")
        + ".xlsx"
    )

    output_path = os.path.join(
        OUTPUT_FOLDER,
        filename
    )

    wb.save(
        output_path
    )

    return output_path


# ============================================================
# HOME
# ============================================================

@app.route("/")
def home():

    return render_template(
        "index.html"
    )


# ============================================================
# GENERATE
# ============================================================

@app.route(
    "/generate",
    methods=["POST"]
)
def generate():

    try:

        uploaded_file = request.files.get(
            "file"
        )

        if not uploaded_file:

            return render_template(
                "index.html",
                error="Please upload the OOO Excel file."
            )

        if not uploaded_file.filename:

            return render_template(
                "index.html",
                error="Please select an Excel file."
            )

        input_path = os.path.join(
            UPLOAD_FOLDER,
            uploaded_file.filename
        )

        uploaded_file.save(
            input_path
        )

        # Read OOO
        records = read_ooo_file(
            input_path
        )

        # Create report
        output_path = create_report(
            records
        )

        # Automatic download
        return send_file(
            output_path,
            as_attachment=True,
            download_name=os.path.basename(
                output_path
            ),
            mimetype=(
                "application/vnd.openxmlformats-"
                "officedocument.spreadsheetml.sheet"
            )
        )

    except Exception as e:

        print(
            "ERROR:",
            repr(e)
        )

        return render_template(
            "index.html",
            error=str(e)
        )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )
