"use strict";
const TeamFlow={team:"",project:"",task:"",copsWorkbook:null,dsrReady:false,workbookReady:false};
const byId=id=>document.getElementById(id);
const showOnly=target=>{[byId("entryFlow"),byId("legacyWorkspace"),byId("copsWorkspace")].forEach(el=>el?.classList.add("d-none"));target?.classList.remove("d-none");};
const setFlowError=message=>{byId("flowError").textContent=message;byId("flowError").classList.toggle("d-none",!message);};
const setCopsBadge=(id,text,style)=>{const badge=byId(id);badge.textContent=text;badge.className=`badge ${style}`;};

function selectTeam(team){
 TeamFlow.team=team;byId("selectedTeamLabel").textContent=team;const cops=team==="COPS";
 byId("projectStep").classList.toggle("cops-project-entry",cops);byId("flowTaskColumn").classList.remove("d-none");byId("flowProjectColumn").className="col-md-6";
 byId("continueProjectBtn").innerHTML=cops?'Generate <i class="bi bi-stars ms-1"></i>':'Search / Continue <i class="bi bi-arrow-right ms-1"></i>';
 byId("teamStep").classList.add("d-none");byId("projectStep").classList.remove("d-none");byId("flowProjectRef").focus();
}
function resetCopsState(){
 TeamFlow.copsWorkbook=null;TeamFlow.dsrReady=false;TeamFlow.workbookReady=false;byId("copsWorkbookUpload").value="";byId("copsFallback").classList.add("d-none");
 byId("previewDsrBtn").disabled=true;byId("downloadDsrBtn").classList.add("disabled");byId("previewCompleteWorkbookBtn").disabled=true;
 setCopsBadge("copsDsrStatus","Waiting","bg-secondary");setCopsBadge("copsWorkbookStatus","Waiting","bg-secondary");setCopsBadge("copsSafetyStatus","Waiting","bg-secondary");
 byId("copsDsrMessage").textContent="Waiting for generation";byId("copsWorkbookMessage").textContent="Waiting for retrieval";byId("copsSafetyMessage").textContent="DSR Report + Workbook Content — waiting";
 byId("copsAgentState").innerHTML="<strong>Waiting for Workbook + DSR</strong>";byId("copsChatStatus").textContent="Waiting for Workbook + DSR";byId("copsContinueChatBtn").disabled=true;
 byId("retryCopsSafetyBtn").classList.add("d-none");showCopsStep(1);hideCopsLoading();
}
function changeProject(){if(TeamFlow.team==="COPS")resetCopsState();else window.WorkbookApp?.resetApplication();showOnly(byId("entryFlow"));byId("teamStep").classList.add("d-none");byId("projectStep").classList.remove("d-none");}
function goHome(){TeamFlow.team="";TeamFlow.project="";TeamFlow.task="";resetCopsState();showOnly(byId("entryFlow"));byId("teamStep").classList.remove("d-none");byId("projectStep").classList.add("d-none");byId("flowProjectRef").value="";byId("flowTaskNumber").value="";setFlowError("");}

async function continueProject(){
 const project=byId("flowProjectRef").value.trim(),task=byId("flowTaskNumber").value.trim();
 if(!project||!task)return setFlowError("Enter both the project reference number and task number.");
 TeamFlow.project=project;TeamFlow.task=task;setFlowError("");
 if(TeamFlow.team!=="COPS"){byId("projectRef").value=project;byId("taskNumber").value=task;showOnly(byId("legacyWorkspace"));byId("fetchWorkbookBtn").click();return;}
 resetCopsState();showOnly(byId("copsWorkspace"));byId("copsContext").textContent=`Project ${project} · Task ${task}`;await prepareCops();
}
function showCopsFallback(taskUrl,message="Automatic workbook retrieval failed. Upload the workbook to continue."){
 byId("copsWorkbookMessage").textContent=message;setCopsBadge("copsWorkbookStatus","Action needed","bg-warning text-dark");byId("copsTaskLink").href=taskUrl||"#";byId("copsTaskLink").classList.toggle("disabled",!taskUrl);byId("copsFallback").classList.remove("d-none");
}
async function prepareCops(){
 showCopsLoading();
 const button=byId("continueProjectBtn");button.disabled=true;setCopsBadge("copsDsrStatus","Generating","bg-primary");setCopsBadge("copsWorkbookStatus","Retrieving","bg-primary");
 byId("copsDsrMessage").textContent="Generating DSR report...";byId("copsWorkbookMessage").textContent="Retrieving complete workbook...";
 try{
  const response=await fetch("/cops/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task})});const data=await response.json();
  if(!response.ok)throw new Error();TeamFlow.dsrReady=true;setCopsBadge("copsDsrStatus","Ready","bg-success");byId("copsDsrMessage").textContent="DSR report generated";
  const dsrQuery=`?project_reference=${encodeURIComponent(TeamFlow.project)}&task_number=${encodeURIComponent(TeamFlow.task)}`;byId("previewDsrBtn").disabled=false;byId("downloadDsrBtn").classList.remove("disabled");byId("downloadDsrBtn").href=`/cops/dsr${dsrQuery}`;
  if(data.workbook_url){window.open(data.workbook_url,"_blank","noopener");monitorCopsDownload(data.expected_filename||"",data.task_url);}else{showCopsFallback(data.task_url);showCopsLoadingError("Workbook download link was not found. Retry or upload the workbook manually.");}
  updateCopsReadiness();
 }catch(_){TeamFlow.dsrReady=false;setCopsBadge("copsDsrStatus","Failed","bg-danger");byId("copsDsrMessage").textContent="DSR generation failed. Please retry or contact the administrator.";setCopsBadge("copsWorkbookStatus","Failed","bg-danger");byId("copsWorkbookMessage").textContent="Workbook retrieval could not start.";showCopsLoadingError("The workbook could not be fetched.");}finally{button.disabled=false;}
}
async function monitorCopsDownload(expectedFilename,taskUrl){
 try{const response=await fetch("/monitor_workbook/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task,expected_filename:expectedFilename,team:"COPS"})});const started=await response.json();if(!response.ok)return showCopsFallback(taskUrl);
  const poll=window.setInterval(async()=>{const result=await fetch("/monitor_workbook/poll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({monitor_id:started.monitor_id})});const data=await result.json();if(data.status==="ready"){window.clearInterval(poll);applyCopsWorkbook(data);}else if(["timeout","cancelled"].includes(data.status)||!result.ok){window.clearInterval(poll);showCopsFallback(taskUrl);showCopsLoadingError("The workbook download did not complete.");}},1500);
 }catch(_){showCopsFallback(taskUrl);showCopsLoadingError("The workbook download could not be monitored.");}
}
function updateCopsReadiness(){if(!(TeamFlow.dsrReady&&TeamFlow.workbookReady))return;byId("copsAgentState").innerHTML='<strong><i class="bi bi-check-circle-fill"></i> Workbook + DSR Ready</strong><span>Ready to generate validation prompt.</span>';byId("copsChatStatus").textContent="Workbook + DSR are attached internally. Ready to continue.";byId("copsContinueChatBtn").disabled=false;runCopsDataSafety();}
async function runCopsDataSafety(){const retry=byId("retryCopsSafetyBtn");retry.disabled=true;retry.classList.add("d-none");setCopsBadge("copsSafetyStatus","Checking","bg-primary");byId("copsSafetyMessage").textContent="Checking complete DSR Report + Workbook Content + Sheet Instructions";try{const response=await fetch("/cops/data_safety",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task,workbook_session_id:TeamFlow.copsWorkbook?.workbook_session_id})});const data=await response.json().catch(()=>({error:`Data Safety returned HTTP ${response.status}.`}));if(!response.ok)throw new Error(data.error||"Data Safety validation failed.");setCopsBadge("copsSafetyStatus",data.has_pii?"Failed":"Passed",data.has_pii?"bg-danger":"bg-success");const types=Object.entries(data.types||{}).map(([name,count])=>`${name.replaceAll("_"," ")}: ${count}`).join(", ");byId("copsSafetyMessage").textContent=data.has_pii?`${data.count} issue(s) detected across complete content${types?` (${types})`:""}`:"DSR Report + Workbook Content checked; no sensitive data found";}catch(error){setCopsBadge("copsSafetyStatus","Error","bg-danger");byId("copsSafetyMessage").textContent=error.message||"Data Safety check could not be completed";}finally{retry.disabled=false;retry.classList.remove("d-none");}}
function applyCopsWorkbook(data){TeamFlow.copsWorkbook=data;TeamFlow.workbookReady=true;setCopsBadge("copsWorkbookStatus","Ready","bg-success");byId("copsWorkbookMessage").textContent="Complete workbook ready";byId("previewCompleteWorkbookBtn").disabled=false;byId("copsFallback").classList.add("d-none");hideCopsLoading();updateCopsReadiness();}
function previewCopsWorkbook(){const workbook=TeamFlow.copsWorkbook;if(!workbook)return;byId("copsPreviewName").textContent=workbook.filename||"Workbook";const tabs=byId("copsPreviewTabs");tabs.replaceChildren();const render=name=>{const table=document.createElement("table");table.className="table table-sm table-bordered";(workbook.sheet_data?.[name]?.preview_rows||[]).forEach(row=>{const tr=document.createElement("tr");row.forEach(cell=>{const td=document.createElement("td");td.textContent=cell?.value??"";tr.appendChild(td);});table.appendChild(tr);});byId("copsPreviewGrid").replaceChildren(table);};(workbook.sheets||[]).forEach((name,index)=>{const button=document.createElement("button");button.className="btn btn-sm btn-outline-primary";button.textContent=name;button.addEventListener("click",()=>render(name));tabs.appendChild(button);if(index===0)render(name);});bootstrap.Modal.getOrCreateInstance(byId("copsWorkbookPreviewModal")).show();}
async function uploadCopsWorkbook(event){const file=event.target.files[0];if(!file)return;const form=new FormData();form.append("workbook",file);form.append("project_reference",TeamFlow.project);form.append("task_number",TeamFlow.task);form.append("team","COPS");setCopsBadge("copsWorkbookStatus","Loading","bg-primary");const response=await fetch("/upload_workbook",{method:"POST",body:form});const data=await response.json();if(!response.ok){setCopsBadge("copsWorkbookStatus","Failed","bg-danger");byId("copsWorkbookMessage").textContent="Workbook upload failed. Please retry.";return;}applyCopsWorkbook(data);}
function showCopsStep(number){const first=number===1;byId("copsStepOneContent").classList.toggle("d-none",!first);byId("copsRovoContent").classList.toggle("d-none",first);byId("copsStepOne").classList.toggle("active",first);byId("copsStepOne").classList.toggle("complete",!first&&TeamFlow.dsrReady&&TeamFlow.workbookReady);byId("copsStepTwo").classList.toggle("active",!first);byId("copsRefreshState").textContent="Ready";}
function showCopsLoading(){byId("copsLoadingOverlay").classList.remove("d-none");byId("copsLoadingSpinner").classList.remove("d-none");byId("copsLoadingProgress").classList.remove("d-none");byId("copsRetryBtn").classList.add("d-none");byId("copsLoadingTitle").textContent="Fetching Workbook…";byId("copsLoadingMessage").textContent="Please wait while we download the latest workbook.";}
function hideCopsLoading(){byId("copsLoadingOverlay")?.classList.add("d-none");}
function showCopsLoadingError(message){byId("copsLoadingOverlay").classList.remove("d-none");byId("copsLoadingSpinner").classList.add("d-none");byId("copsLoadingProgress").classList.add("d-none");byId("copsLoadingTitle").textContent="Workbook download failed";byId("copsLoadingMessage").textContent=message;byId("copsRetryBtn").classList.remove("d-none");}
async function previewDsr(){const body=byId("copsTextModalBody");body.textContent="Loading DSR report…";byId("copsTextModalTitle").textContent="DSR Report Preview";byId("copsTextModalTeam").textContent="COPS";bootstrap.Modal.getOrCreateInstance(byId("copsTextModal")).show();const query=`?project_reference=${encodeURIComponent(TeamFlow.project)}&task_number=${encodeURIComponent(TeamFlow.task)}`;try{const response=await fetch(`/cops/dsr/preview${query}`),data=await response.json();if(!response.ok)throw new Error(data.error);const wrapper=document.createElement("div");wrapper.className="cops-document-preview";data.paragraphs.forEach(text=>{const p=document.createElement("p");p.textContent=text;wrapper.appendChild(p);});data.tables.forEach(rows=>{const table=document.createElement("table");table.className="table table-sm table-bordered";rows.forEach(cells=>{const tr=document.createElement("tr");cells.forEach(value=>{const td=document.createElement("td");td.textContent=value;tr.appendChild(td);});table.appendChild(tr);});wrapper.appendChild(table);});body.replaceChildren(wrapper);}catch(error){body.textContent=error.message||"Unable to preview the DSR report.";}}
async function showInstructions(){byId("copsTextModalTitle").textContent="Sheet Instructions";byId("copsTextModalTeam").textContent="Team: COPS";byId("copsTextModalBody").textContent="Loading instructions…";bootstrap.Modal.getOrCreateInstance(byId("copsTextModal")).show();const response=await fetch("/sheet_instructions/COPS"),data=await response.json();byId("copsTextModalBody").textContent=response.ok?data.instructions:(data.error||"Unable to load instructions.");}
function refreshChat(){const button=byId("refreshCopsChat"),state=byId("copsRefreshState"),first=!byId("copsStepOneContent").classList.contains("d-none"),frame=byId(first?"copsRovoFrameOne":"copsRovoFrameTwo");if(button.disabled)return;button.disabled=true;state.textContent="Refreshing…";const source=frame.src,finish=(message)=>{state.textContent=message;button.disabled=false;frame.onload=null;frame.onerror=null;};let resetting=true;frame.onload=()=>{if(resetting){resetting=false;frame.src=source;return;}finish("Ready");};frame.onerror=()=>finish("Refresh failed");try{frame.src="about:blank";}catch(_){finish("Refresh failed");}}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-team]").forEach(button=>button.addEventListener("click",()=>selectTeam(button.dataset.team)));document.querySelectorAll("[data-go-home]").forEach(button=>button.addEventListener("click",goHome));document.querySelectorAll("[data-change-project]").forEach(button=>button.addEventListener("click",changeProject));byId("backToTeamsBtn").addEventListener("click",goHome);byId("continueProjectBtn").addEventListener("click",continueProject);byId("copsWorkbookUpload").addEventListener("change",uploadCopsWorkbook);byId("previewCompleteWorkbookBtn").addEventListener("click",previewCopsWorkbook);byId("previewDsrBtn").addEventListener("click",previewDsr);byId("openCopsInstructionsBtn").addEventListener("click",showInstructions);byId("refreshCopsChat").addEventListener("click",refreshChat);byId("retryCopsSafetyBtn").addEventListener("click",runCopsDataSafety);byId("copsRetryBtn").addEventListener("click",prepareCops);byId("copsStepOne").addEventListener("click",()=>showCopsStep(1));byId("copsStepTwo").addEventListener("click",()=>showCopsStep(2));byId("copsContinueChatBtn").addEventListener("click",()=>showCopsStep(2));byId("copsBackChatBtn").addEventListener("click",()=>showCopsStep(1));});
