"use strict";
const TeamFlow={team:"",project:"",task:"",copsWorkbook:null,dsrReady:false,workbookReady:false,stepOneComplete:false};
const byId=id=>document.getElementById(id);
const showOnly=target=>{[byId("entryFlow"),byId("legacyWorkspace"),byId("copsWorkspace")].forEach(el=>el?.classList.add("d-none"));target?.classList.remove("d-none");};
const setFlowError=message=>{byId("flowError").textContent=message;byId("flowError").classList.toggle("d-none",!message);};
const setCopsBadge=(id,text,style)=>{const badge=byId(id);badge.textContent=text;badge.className=`badge ${style}`;};

function selectTeam(team){
 TeamFlow.team=team;byId("selectedTeamLabel").textContent=team;const cops=team==="COPS";
 byId("projectStep").classList.toggle("cops-project-entry",cops);byId("flowTaskColumn").classList.remove("d-none");byId("flowProjectColumn").className="col-md-6";
 byId("continueProjectBtn").innerHTML=cops?'Generate <i class="bi bi-stars ms-1"></i>':'Search / Continue <i class="bi bi-arrow-right ms-1"></i>';
 byId("teamStep").classList.add("d-none");byId("projectStep").classList.remove("d-none");byId("flowProjectRef").focus();
}
function resetCopsState(){
 TeamFlow.copsWorkbook=null;TeamFlow.dsrReady=false;TeamFlow.workbookReady=false;TeamFlow.stepOneComplete=false;byId("copsWorkbookUpload").value="";byId("copsFallback").classList.add("d-none");
 byId("previewDsrBtn").disabled=true;byId("downloadDsrBtn").classList.add("disabled");byId("previewCompleteWorkbookBtn").disabled=true;
 setCopsBadge("copsDsrStatus","Waiting","bg-secondary");setCopsBadge("copsWorkbookStatus","Waiting","bg-secondary");setCopsBadge("copsSafetyStatus","Waiting","bg-secondary");
 byId("copsDsrMessage").textContent="Waiting for generation";byId("copsWorkbookMessage").textContent="Waiting for retrieval";byId("copsSafetyMessage").textContent="DSR Report + Workbook Content — waiting";
 byId("retryCopsSafetyBtn").classList.add("d-none");byId("copsMaskedData").classList.add("d-none");byId("copsMaskedDataList").replaceChildren();byId("copsStepTwo").disabled=false;showCopsStep(1);hideCopsLoading();
}
function changeProject(){if(TeamFlow.team==="COPS")resetCopsState();else window.WorkbookApp?.resetApplication();showOnly(byId("entryFlow"));byId("teamStep").classList.add("d-none");byId("projectStep").classList.remove("d-none");}
function goHome(){TeamFlow.team="";TeamFlow.project="";TeamFlow.task="";resetCopsState();showOnly(byId("entryFlow"));byId("teamStep").classList.remove("d-none");byId("projectStep").classList.add("d-none");byId("flowProjectRef").value="";byId("flowTaskNumber").value="";setFlowError("");}

async function continueProject(){
 const project=byId("flowProjectRef").value.trim(),task=byId("flowTaskNumber").value.trim();
 if(!project||!task)return setFlowError("Enter both the project reference number and task number.");
 TeamFlow.project=project;TeamFlow.task=task;setFlowError("");
 if(TeamFlow.team!=="COPS"){byId("projectRef").value=project;byId("taskNumber").value=task;showOnly(byId("legacyWorkspace"));byId("fetchWorkbookBtn").click();return;}
 resetCopsState();showOnly(byId("copsWorkspace"));byId("copsContext").textContent=`Project ${project} · Task ${task}`;await prepareCops();
}
function showCopsFallback(taskUrl,message="Workbook could not be downloaded automatically."){
 hideCopsLoading();byId("copsWorkbookMessage").textContent=message;setCopsBadge("copsWorkbookStatus","Action needed","bg-warning text-dark");byId("copsTaskLink").href=taskUrl||"#";byId("copsTaskLink").classList.toggle("disabled",!taskUrl);byId("copsFallback").classList.remove("d-none");
}
async function prepareCops(){
 showCopsLoading();
 const button=byId("continueProjectBtn");button.disabled=true;setCopsBadge("copsDsrStatus","Generating","bg-primary");setCopsBadge("copsWorkbookStatus","Retrieving","bg-primary");
 byId("copsDsrMessage").textContent="Generating DSR report...";byId("copsWorkbookMessage").textContent="Retrieving complete workbook...";
 try{
  const response=await fetch("/cops/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task})});const data=await response.json();
  if(!response.ok)throw new Error();TeamFlow.dsrReady=true;setCopsBadge("copsDsrStatus","Ready","bg-success");byId("copsDsrMessage").textContent="DSR report generated";
  const dsrQuery=`?project_reference=${encodeURIComponent(TeamFlow.project)}&task_number=${encodeURIComponent(TeamFlow.task)}`;byId("previewDsrBtn").disabled=false;byId("downloadDsrBtn").classList.remove("disabled");byId("downloadDsrBtn").href=`/cops/dsr${dsrQuery}`;
  if(data.workbook_url){window.open(data.workbook_url,"_blank","noopener");monitorCopsDownload(data.expected_filename||"",data.task_url);}else showCopsFallback(data.task_url);
  updateCopsReadiness();
 }catch(_){TeamFlow.dsrReady=false;setCopsBadge("copsDsrStatus","Failed","bg-danger");byId("copsDsrMessage").textContent="DSR generation failed. Please retry or contact the administrator.";showCopsFallback(null);}finally{button.disabled=false;}
}
async function monitorCopsDownload(expectedFilename,taskUrl){
 try{const response=await fetch("/monitor_workbook/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task,expected_filename:expectedFilename,team:"COPS"})});const started=await response.json();if(!response.ok)return showCopsFallback(taskUrl);
  const poll=window.setInterval(async()=>{const result=await fetch("/monitor_workbook/poll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({monitor_id:started.monitor_id})});const data=await result.json();if(data.status==="ready"){window.clearInterval(poll);applyCopsWorkbook(data);}else if(["timeout","cancelled"].includes(data.status)||!result.ok){window.clearInterval(poll);showCopsFallback(taskUrl);}},1500);
 }catch(_){showCopsFallback(taskUrl);}
}
function updateCopsReadiness(){if(!(TeamFlow.dsrReady&&TeamFlow.workbookReady))return;runCopsDataSafety();}
async function runCopsDataSafety(){const retry=byId("retryCopsSafetyBtn");retry.disabled=true;retry.classList.add("d-none");byId("copsMaskedData").classList.add("d-none");setCopsBadge("copsSafetyStatus","CHECKING","bg-primary");byId("copsSafetyMessage").textContent="Checking and masking sensitive data…";try{const response=await fetch("/cops/data_safety",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:TeamFlow.project,task_number:TeamFlow.task,workbook_session_id:TeamFlow.copsWorkbook?.workbook_session_id})});const data=await response.json().catch(()=>({error:`Data Safety returned HTTP ${response.status}.`}));if(!response.ok)throw new Error(data.error||"Data Safety validation failed.");setCopsBadge("copsSafetyStatus","PASSED","bg-success");const count=Number(data.count)||0;byId("copsSafetyMessage").textContent=count?`${count} sensitive ${count===1?"item":"items"} automatically masked`:"No sensitive data detected — content is safe";renderCopsMaskedData(data.findings||[]);}catch(error){setCopsBadge("copsSafetyStatus","FAILED","bg-danger");byId("copsSafetyMessage").textContent=error.message||"Data Safety masking could not be completed";retry.disabled=false;retry.classList.remove("d-none");}}
function renderCopsMaskedData(findings){const panel=byId("copsMaskedData"),list=byId("copsMaskedDataList");list.replaceChildren();if(!findings.length){panel.classList.add("d-none");return;}findings.forEach(finding=>{const row=document.createElement("div");row.className="cops-masked-entry";const type=document.createElement("span"),masked=document.createElement("code"),location=document.createElement("span"),check=document.createElement("span");type.textContent=finding.type==="ssn"?"SSN":"Card";const lastFour=String(finding.masked_preview||"").slice(-4);masked.textContent=finding.type==="ssn"?`***-**-${lastFour}`:`**** **** **** ${lastFour}`;location.textContent=[finding.section,finding.worksheet].filter(Boolean).join(" · ")||"Complete content";check.className="cops-masked-check";check.textContent="✓ Masked";row.append(type,masked,location,check);list.appendChild(row);});panel.classList.remove("d-none");}
function applyCopsWorkbook(data){const filename=data.original_filename||data.workbook_name||data.filename||"Workbook.xlsx";if(TeamFlow.copsWorkbook?.workbook_session_id===data.workbook_session_id)return;TeamFlow.copsWorkbook={...data,filename};TeamFlow.workbookReady=true;setCopsBadge("copsWorkbookStatus","Ready","bg-success");byId("copsWorkbookMessage").textContent=filename;byId("previewCompleteWorkbookBtn").disabled=false;byId("copsFallback").classList.add("d-none");hideCopsLoading();updateCopsReadiness();}
function previewCopsWorkbook(){const workbook=TeamFlow.copsWorkbook;if(!workbook)return;byId("copsPreviewName").textContent=workbook.filename||"Workbook";const tabs=byId("copsPreviewTabs");tabs.replaceChildren();const render=name=>{const table=document.createElement("table");table.className="table table-sm table-bordered";(workbook.sheet_data?.[name]?.preview_rows||[]).forEach(row=>{const tr=document.createElement("tr");row.forEach(cell=>{const td=document.createElement("td");td.textContent=cell?.value??"";tr.appendChild(td);});table.appendChild(tr);});byId("copsPreviewGrid").replaceChildren(table);};(workbook.sheets||[]).forEach((name,index)=>{const button=document.createElement("button");button.className="btn btn-sm btn-outline-primary";button.textContent=name;button.addEventListener("click",()=>render(name));tabs.appendChild(button);if(index===0)render(name);});bootstrap.Modal.getOrCreateInstance(byId("copsWorkbookPreviewModal")).show();}
async function processCopsWorkbookFile(file){if(!file||!/^\.xls(x|m)?$/i.test(file.name))return;byId("copsWorkbookMessage").textContent="✓ Workbook detected — Processing workbook…";setCopsBadge("copsWorkbookStatus","Processing","bg-primary");showCopsLoading();byId("copsLoadingTitle").textContent="Processing workbook…";byId("copsLoadingMessage").textContent="Workbook detected. Validating workbook...";const form=new FormData();form.append("workbook",file);form.append("project_reference",TeamFlow.project);form.append("task_number",TeamFlow.task);form.append("team","COPS");try{const response=await fetch("/upload_workbook",{method:"POST",body:form}),data=await response.json();if(!response.ok)throw new Error(data.error||"Workbook upload failed.");byId("copsWorkbookMessage").textContent="✓ Workbook uploaded successfully — Validating workbook…";applyCopsWorkbook(data);}catch(error){hideCopsLoading();setCopsBadge("copsWorkbookStatus","Failed","bg-danger");byId("copsWorkbookMessage").textContent=error.message;}}
async function uploadCopsWorkbook(event){await processCopsWorkbookFile(event.target.files[0]);event.target.value="";}
function showCopsStep(number){const first=number===1;byId("copsStepOneContent").classList.toggle("d-none",!first);byId("copsRovoContent").classList.toggle("d-none",first);byId("copsStepOne").classList.toggle("active",first);byId("copsStepOne").classList.remove("complete");byId("copsStepTwo").classList.toggle("active",!first);byId("copsStepTwo").classList.remove("complete");byId("copsRefreshState").textContent="Ready";}
function showCopsLoading(){byId("copsLoadingOverlay").classList.remove("d-none");byId("copsLoadingSpinner").classList.remove("d-none");byId("copsRetryBtn").classList.add("d-none");byId("copsLoadingTitle").textContent="Fetching Workbook...";byId("copsLoadingMessage").textContent="Please wait while we download the latest workbook.";}
function hideCopsLoading(){byId("copsLoadingOverlay")?.classList.add("d-none");}
function showCopsLoadingError(message){byId("copsLoadingOverlay").classList.remove("d-none");byId("copsLoadingSpinner").classList.add("d-none");byId("copsLoadingTitle").textContent="Workbook download failed";byId("copsLoadingMessage").textContent=message;byId("copsRetryBtn").classList.remove("d-none");}
async function previewDsr(){const body=byId("copsTextModalBody");body.textContent="Loading DSR report…";byId("copsTextModalTitle").textContent="DSR Report Preview";byId("copsTextModalTeam").textContent="COPS";bootstrap.Modal.getOrCreateInstance(byId("copsTextModal")).show();const query=`?project_reference=${encodeURIComponent(TeamFlow.project)}&task_number=${encodeURIComponent(TeamFlow.task)}`;try{const response=await fetch(`/cops/dsr/preview${query}`),data=await response.json();if(!response.ok)throw new Error(data.error);const wrapper=document.createElement("div");wrapper.className="cops-document-preview";data.paragraphs.forEach(text=>{const p=document.createElement("p");p.textContent=text;wrapper.appendChild(p);});data.tables.forEach(rows=>{const table=document.createElement("table");table.className="table table-sm table-bordered";rows.forEach(cells=>{const tr=document.createElement("tr");cells.forEach(value=>{const td=document.createElement("td");td.textContent=value;tr.appendChild(td);});table.appendChild(tr);});wrapper.appendChild(table);});body.replaceChildren(wrapper);}catch(error){body.textContent=error.message||"Unable to preview the DSR report.";}}
async function showInstructions(){byId("copsTextModalTitle").textContent="Sheet Instructions";byId("copsTextModalTeam").textContent="Team: COPS";byId("copsTextModalBody").textContent="Loading instructions…";bootstrap.Modal.getOrCreateInstance(byId("copsTextModal")).show();const response=await fetch("/sheet_instructions/COPS"),data=await response.json();byId("copsTextModalBody").textContent=response.ok?data.instructions:(data.error||"Unable to load instructions.");}
function refreshChat(){const button=byId("refreshCopsChat"),state=byId("copsRefreshState"),first=!byId("copsStepOneContent").classList.contains("d-none"),frame=byId(first?"copsRovoFrameOne":"copsRovoFrameTwo");if(button.disabled)return;button.disabled=true;state.textContent="Refreshing…";const source=frame.src,finish=(message)=>{state.textContent=message;button.disabled=false;frame.onload=null;frame.onerror=null;};let resetting=true;frame.onload=()=>{if(resetting){resetting=false;frame.src=source;return;}finish("Ready");};frame.onerror=()=>finish("Refresh failed");try{frame.src="about:blank";}catch(_){finish("Refresh failed");}}
function trustedRovoOrigin(frame){try{const url=new URL(frame.src,window.location.href);return url.protocol==="about:"?window.location.origin:url.origin;}catch(_){return null;}}
function attachSameOriginRovoDrop(frame){try{const documentRoot=frame.contentDocument;if(!documentRoot||documentRoot.documentElement.dataset.copsDropSync)return;documentRoot.documentElement.dataset.copsDropSync="true";documentRoot.addEventListener("drop",event=>{const file=[...(event.dataTransfer?.files||[])].find(item=>/^\.xls(x|m)?$/i.test(item.name));if(file)processCopsWorkbookFile(file);});}catch(_){/* Cross-origin Rovo must use the validated postMessage integration below. */}}
function receiveRovoWorkbook(event){const frame=byId("copsRovoFrameOne"),expectedOrigin=trustedRovoOrigin(frame),message=event.data;if(!expectedOrigin||event.origin!==expectedOrigin||event.source!==frame.contentWindow||!message||message.type!=="rovo-workbook-dropped")return;const file=message.file,metadata=message.metadata||{};if(!(file instanceof File)||!/^\.xls(x|m)?$/i.test(file.name)||metadata.name!==file.name||Number(metadata.size)!==file.size)return;processCopsWorkbookFile(file);}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-team]").forEach(button=>button.addEventListener("click",()=>selectTeam(button.dataset.team)));document.querySelectorAll("[data-go-home]").forEach(button=>button.addEventListener("click",goHome));document.querySelectorAll("[data-change-project]").forEach(button=>button.addEventListener("click",changeProject));byId("backToTeamsBtn").addEventListener("click",goHome);byId("continueProjectBtn").addEventListener("click",continueProject);byId("copsWorkbookUpload").addEventListener("change",uploadCopsWorkbook);byId("previewCompleteWorkbookBtn").addEventListener("click",previewCopsWorkbook);byId("previewDsrBtn").addEventListener("click",previewDsr);byId("openCopsInstructionsBtn").addEventListener("click",showInstructions);byId("refreshCopsChat").addEventListener("click",refreshChat);byId("retryCopsSafetyBtn").addEventListener("click",runCopsDataSafety);byId("copsRetryBtn").addEventListener("click",prepareCops);byId("retryCopsDownloadBtn").addEventListener("click",prepareCops);byId("copsStepOne").addEventListener("click",()=>showCopsStep(1));byId("copsStepTwo").addEventListener("click",()=>showCopsStep(2));const cta=byId("copsStepOneCta");cta.addEventListener("click",()=>showCopsStep(2));cta.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();showCopsStep(2);}});byId("copsBackChatBtn").addEventListener("click",()=>showCopsStep(1));const firstFrame=byId("copsRovoFrameOne");firstFrame.addEventListener("load",()=>attachSameOriginRovoDrop(firstFrame));attachSameOriginRovoDrop(firstFrame);window.addEventListener("message",receiveRovoWorkbook);});
